global_frame: map         # Once odom to base_link is robust fix this to odom
rolling_window: true

plugins:
  - {name: rgbd_obstacle_layer,     type: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}

