# Joint state controller - publishes joint states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Differential drive controller for 4-wheel drive
mars_rover_diff_drive_controller:
  type: diff_drive_controller/DiffDriveController
  
  # Wheel joints
  left_wheel: ['wheel_fl', 'wheel_rl']
  right_wheel: ['wheel_fr', 'wheel_rr']
  
  # Publish rate
  publish_rate: 50
  
  # Odometry settings
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
  
  # Robot physical parameters (adjust based on your rover)
  wheel_separation: 0.5  # Distance between left and right wheels (meters)
  wheel_radius: 0.1      # Wheel radius (meters)
  
  # Velocity limits
  linear:
    x:
      has_velocity_limits: true
      max_velocity: 1.0           # m/s
      min_velocity: -1.0          # m/s
      has_acceleration_limits: true
      max_acceleration: 0.8       # m/s^2
  angular:
    z:
      has_velocity_limits: true
      max_velocity: 2.0           # rad/s
      has_acceleration_limits: true
      max_acceleration: 1.5       # rad/s^2
  
  # Frame IDs
  base_frame_id: base_link
  odom_frame_id: odom
  enable_odom_tf: true
  
  # Command timeout
  cmd_vel_timeout: 0.5
